# Automatically publish a package to GitHub Packages and the NPM Registry when a release is created

name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/
      - run: pnpm install --frozen-lockfile
      - run: pnpm autopublish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_TOKEN_NPM}}

  # publish-gpr:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: pnpm/action-setup@v4
  #       with:
  #         version: 9
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         cache: 'pnpm'
  #         registry-url: https://npm.pkg.github.com/
  #         scope: '@wakgames'
  #     - run: pnpm install --frozen-lockfile
  #     - run: pnpm compile
  #     - run: echo registry=https://npm.pkg.github.com/WakGames >> .npmrc
  #     - run: pnpm publish --no-git-checks
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.PUBLISH_TOKEN_GITHUB}}
